# Generated by Django 3.2.7 on 2021-09-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_delete_getintouch'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='posted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
